### ISSUE TITLE
RFE: Add deterministic option for reduce, scan, etc.

### ISSUE THREAD

**Issue by ekelsen** [NVIDIA/cub#108]
The default work sharing strategy on sm_35+ isn't deterministic by default.  Would be great to have the option to use the even_share strategy to get determinism even if it's a little slower.

**Comment by dumerrill** [comment]
Commit [f558c6d](https://github.com/NVlabs/cub/commit/f558c6d3318f18d6652c50c01eca640e09ca1f5a) resolves this issue for all variants of device-wide reduction.  (Block reduction, warp-wide reduction, and all variants of prefix scan have always been deterministic.)

Note that all CUB device-wide algorithms are "run-to-run" deterministic for pseudo-associative reduction operators (like floating point addition), i.e., their results are consistent across multiple runs on the same device.  Floating point reduction may produce slightly different results on different devices having different numbers of SMs or different compute capabilities (where CUB might use different tile sizes.)

**Comment by lilohuang** [comment]
@dumerrill could be incorrect in 2022 especially for some device-wide operations. see details in https://github.com/NVIDIA/cub/issues/441 and https://github.com/NVIDIA/thrust/issues/1587#issuecomment-1021471946

CC @allisonvacanti @senior-zero

**Comment by lilohuang** [comment]
@dumerrill comment might be incorrect in 2022 especially for some device-wide operations. see details in https://github.com/NVIDIA/cub/issues/441 and https://github.com/NVIDIA/thrust/issues/1587#issuecomment-1021471946

CC @allisonvacanti @senior-zero

**Comment by allisonvacanti** [comment]
Closing after all, we'll let this old RFE rest. I've filed a new issue for the regressions at #471.
