### ISSUE TITLE
Illegal memory access in HeadsAndTails BlockDiscontinuity

### ISSUE THREAD

**Issue by llena1** [NVIDIA/cub#120]
Initialization of `preds[0]` in `block_discontinuity.cuh` line 750 tries to access element -1 in thread 0
```cpp
        // Set flag for first thread-item
        preds[0] = temp_storage.last_items[linear_tid - 1];
```

**Comment by dumerrill** [comment]
This is by design.  We can save ourselves the work of guarding against that because temp_storage.last_items is padded above it by temp_storage.first_items.  And if you look below, preds[0] is never used in thread0.

Are you actually getting an illegal memory access?

**Comment by allisonvacanti** [comment]
Expiring. If this is still an issue, please reopen and respond to Duane's question above.
