### ISSUE TITLE
DeviceSegmentedReduce for constant size segments

### ISSUE THREAD

**Issue by sh1ng** [NVIDIA/cub#143]
Let's say I have constant size for all segments.
In you example it's like 
```
#include <cub/cub.cuh>   // or equivalently <cub/device/device_radix_sort.cuh>
// Declare, allocate, and initialize device-accessible pointers for input and output
int num_segments;   // e.g., 5
int *d_offsets;     // e.g., [0, 10, 20, 30, 40], size always 10
int *d_in;          // e.g., [8, 6, 7, 5, 3, 0, 9]
int *d_out;         // e.g., [-, -, -]
...
// Determine temporary device storage requirements
void     *d_temp_storage = NULL;
size_t   temp_storage_bytes = 0;
cub::DeviceSegmentedReduce::Sum(d_temp_storage, temp_storage_bytes, d_in, d_out,
    num_segments, d_offsets, d_offsets + 1);
// Allocate temporary storage
cudaMalloc(&d_temp_storage, temp_storage_bytes);
// Run sum-reduction
cub::DeviceSegmentedReduce::Sum(d_temp_storage, temp_storage_bytes, d_in, d_out,
    num_segments, d_offsets, d_offsets + 1);
// d_out <-- [21, 0, 17]
```

Is it possible to execute  `DeviceSegmentedReduce` without allocation memory  for `d_offsets`?

**Comment by allisonvacanti** [comment]
The current version of CUB takes an iterator for the offsets instead of a pointer, so you should be make this work using `thrust::counting_iterator` to generate a sequence and `thrust::transform_iterator` to scale them to your desired offsets.

**Comment by leofang** [comment]
Thanks for the tip, @allisonvacanti! We also need this to eliminate a temporary array 🙂

**Comment by allisonvacanti** [comment]
No problem :) I should mention that CUB also has versions of these, `cub::CountingInputIterator` / `cub::TransformInputIterator`, I just thought of the thrust ones first.
