### ISSUE TITLE
Can different block (for block level primitive) operate on variant length of data

### ISSUE THREAD

**Issue by limin2021** [NVIDIA/cub#146]
As you can see, cub provides many block level primitives, i.e. blockradixsort. I want to know: Can different block (for block level primitive) operate on variant length of data? In this context, how to the value of  BLOCK_THREADS  and ITEMS_PER_THREAD?
  In the example of "example_block_radix_sort" , the length of data for a block to handle is TILE (TILE is got by BLOCK_THREADS * ITEMS_PER_THREAD).  In real applications, TILE is first fixed, and users need to choose appropriate  BLOCK_THREADS, how to deal with when TILE is not a multiple of  BLOCK_THREADS?

**Comment by allisonvacanti** [comment]
I'm having trouble understanding the question. Do you have a code example that highlights the issue?
