### ISSUE TITLE
Compiler warnings on temp storage

### ISSUE THREAD

**Issue by jipe4153** [NVIDIA/cub#159]
BlockScan storage variable causes warnings:

``
__shared__ typename cub::BlockScan<int, X_THREADS> temp_storage;
``

 warning: __shared__ memory variable with non-empty constructor or destructor (potential race between threads)

**Comment by allisonvacanti** [comment]
This looks like a typo -- did you mean to use `cub::BlockScan<...>::TempStorage`? https://www.godbolt.org/z/8h5T93
