### ISSUE TITLE
Query: Performance of key value radix sort?

### ISSUE THREAD

**Issue by avinashcpandey** [NVIDIA/cub#165]
I see key value Radix sort performance on Nvidia GPU from below link
https://nvlabs.github.io/cub/structcub_1_1_device_radix_sort.html
Which is 1.41 billion keys/sec on GTX titan.
Is it the max performance you can get with current algo?
Thrust doesn't have ant performance documentation of key value radix sort ?

**Comment by allisonvacanti** [comment]
All of the existing tunings and benchmarks are very out of date. We're in the process of retuning and benchmarking Thrust + CUB. Once we finish that work we'll be in a better position to answer these sorts of questions.

**Comment by allisonvacanti** [comment]
This is effectively the same underlying issue as #80, please follow that issue for updates.
