### ISSUE TITLE
Examples within visual studio failing

### ISSUE THREAD

**Issue by Eths33** [NVIDIA/cub#174]
The sample code is not working for me on windows, any ideas?
I created a new CUDA project in Visual studio, then added the include directories. I'm thinking there is another step.

**Update**: tested on Linux and it works as intended. If anyone does know the correct setup to run the examples on windows it would be appreciated. If I have time, I will work more on it and post what I find. I wrote my own reduction code as a fix to my issue so this is no longer a top priority. 

Output:

Using device 0: GeForce RTX 2080 Ti (PTX version 750, SM750, 68 SMs, 9244 free / 11264 total MB physmem, 616.000 GB/s @ 7000000 kHz mem clock, ECC off)
Input data: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, ......... etc.

BlockReduce algorithm BLOCK_REDUCE_RAKING on 1024 items (100 timing iterations, 1 blocks, 1024 threads, 1 items per thread, 0 SM occupancy):
        Aggregate: Reference:
8166,

Computed:
0,

INCORRECT: [0]: 0 != 8166FAIL

(.../example_block_reduce.cu: 189)

Thanks

**Comment by allisonvacanti** [comment]
I've recently run this example from the current `main` branch on both MSVC 2017 and MSVC 2019 with no issues. Please reopen and provide more detail (compiler versions, CUB versions, etc) if you're still encountering this problem.
