### ISSUE TITLE
Compilation with Clang + Linking with NVCC gives multiple definitions for EmptyKernel

### ISSUE THREAD

**Issue by reguly** [NVIDIA/cub#183]
The EmptyKernel in util_device.cuh gives me multiple definition errors when linking.
nvlink error   : Multiple definition of '_ZN3cubL11EmptyKernelIvEEvv' in 'CMakeFiles/covid.dir/src/tools/randomGenerator.cpp.o', first defined in 'CMakeFiles/covid.dir/src/agentData/PPStateTypes.cpp.o'
nvlink fatal   : merge_elf failed

I am using Clang 10, with -fcuda-rdc, and then the linking has to be done (it seems) using nvcc, where I use -rdc true. 

Is there perhaps a workaround or a fix for this?

**Comment by MrBurmark** [comment]
I should mention that I'm not associated with this repo but I have seen the same problem when compiling cuda code with clang.
This appears to be a clang issue, and if you take a look at the generated code you can see that clang selects the wrong linkage (not weak linkage) for global function templates.
You can work around this by not instantiating global function templates with the same template arguments in different translation units.

**Comment by allisonvacanti** [comment]
We currently don't have the resources to officially support Clang CUDA at this time, so this isn't something that we're likely to fix.

That said, I will accept patches for Clang CUDA support from the community.

From @MrBurmark's response, it sounds like this is a bug in Clang. Please report it there.
