### ISSUE TITLE
Can't build on a system where nvcc doesn't work with default host compiler

### ISSUE THREAD

**Issue by jlebar** [NVIDIA/cub#197]
Tested at d106ddb991a56c3df1b6d51b2409e36ba8181ce4.

My default gcc is gcc 9.3.  My cuda only works with gcc <= 8.x.

The normal cmake way of working around this is to specify `-DCMAKE_CUDA_HOST_COMPILER=/usr/bin/g++-8`.  But cub doesn't like this, asks that I set `-DCMAKE_CXX_COMPILER=/usr/bin/g++-8` instead.  No prob, but that *also* doesn't work.

What seems to be happening is, *before* the cmake file checks that you didn't set CUDA_HOST_COMPILER, the cmake cuda business runs and checks that nvcc works.  But at that point it *needs* CUDA_HOST_COMPILER to be set.

```
❯ git clean -xdf; cmake -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc -DCMAKE_CXX_COMPILER=/usr/bin/g++-8 CMakeLists.txt

Removing CMakeCache.txt
Removing CMakeFiles/
-- The CUDA compiler identification is unknown
-- The CXX compiler identification is GNU 8.4.0
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- broken
CMake Error at /usr/share/cmake-3.16/Modules/CMakeTestCUDACompiler.cmake:46 (message):
  The CUDA compiler

    "/usr/local/cuda/bin/nvcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /usr/local/google/home/jlebar/code/cub/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/make cmTC_a786b/fast && /usr/bin/make -f CMakeFiles/cmTC_a786b.dir/build.make CMakeFiles/cmTC_a786b.dir/build
    make[1]: Entering directory '/usr/local/google/home/jlebar/code/cub/CMakeFiles/CMakeTmp'
    Building CUDA object CMakeFiles/cmTC_a786b.dir/main.cu.o
    /usr/local/cuda/bin/nvcc     -x cu -c /usr/local/google/home/jlebar/code/cub/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_a786b.dir/main.cu.o
    In file included from /usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_runtime.h:83,
                     from <command-line>:
    /usr/local/cuda/bin/../targets/x86_64-linux/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
      138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
          |  ^~~~~
    make[1]: *** [CMakeFiles/cmTC_a786b.dir/build.make:66: CMakeFiles/cmTC_a786b.dir/main.cu.o] Error 1
    make[1]: Leaving directory '/usr/local/google/home/jlebar/code/cub/CMakeFiles/CMakeTmp'
    make: *** [Makefile:121: cmTC_a786b/fast] Error 2





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)


-- Configuring incomplete, errors occurred!
See also "/usr/local/google/home/jlebar/code/cub/CMakeFiles/CMakeOutput.log".
See also "/usr/local/google/home/jlebar/code/cub/CMakeFiles/CMakeError.log".
```

Notice how it's running `/usr/local/cuda/bin/nvcc     -x cu -c /usr/local/google/home/jlebar/code/cub/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_a786b.dir/main.cu.o` and not passing -ccbin to the nvcc invocation.

**Comment by jlebar** [comment]
(Of course one can just hack the cmake file; this isn't blocking me.)

**Comment by allisonvacanti** [comment]
I'm not a fan of how we currently micromanage the compiler settings in our CMake code. @brycelelbach and @griwes tell me it's necessary -- I'll let one of them explain the reasons behind this.

In 620de2a15d19aeaec13e6669a902c442b6133279, I updated the check to be a bit more forgiving, see https://github.com/NVIDIA/cub/blob/main/cmake/CubCudaConfig.cmake#L1-L2. It should now work so long as both `CMAKE_CXX_COMPILER` and `CMAKE_CUDA_HOST_COMPILER` are set to the same variable.

I've tested this out locally just now and it works for the `cmake` invocation in the original issue, so I'll close this. Feel free to reopen if you're still hitting problems from this.
