### ISSUE TITLE
Example for integer radix-based argsort?

### ISSUE THREAD

**Issue by proteneer** [NVIDIA/cub#206]
I was wondering if anyone had suggestions on how to implement an unsigned integer radix argsort in cub similar to what we can do with cupy/thrust:

https://github.com/cupy/cupy/blob/a118905a7976079db8726001a3983d520847cb52/cupy/cuda/cupy_thrust.cu#L336

Maybe I'm missing something obvious but it wasn't super clear how to do this from the tutorial. The documentation says:

"""
DeviceRadixSort can sort all of the built-in C++ numeric primitive types (unsigned char, int, double, etc.) as well as CUDA's __half half-precision floating-point type. Although the direct radix sorting method can only be applied to unsigned integral types, DeviceRadixSort is able to sort signed and floating-point types via simple bit-wise transformations that ensure lexicographic key ordering.
"""

But is there a way to do this for tuples where the first element is the key and the second is an auxiliary element to be carried along?

**Comment by allisonvacanti** [comment]
> But is there a way to do this for tuples where the first element is the key and the second is an auxiliary element to be carried along?

Sounds like you want [`cub::DeviceRadixSort::SortPairs`](https://nvlabs.github.io/cub/structcub_1_1_device_radix_sort.html#a9e14a29dc4ba6d68dc804bc6b0da7dd4), which sorts key/value pairs by key, but this implementation requires that the keys and values are in separate arrays of contiguous memory. Radix sorting a single array containing structs of key/value pairs is not supported, you'd need to split the input data.

If you can't change the input key/value pair array, you could also create a temporary array containing just the keys and use the array of full key/value pairs as the values for `SortPairs`. This will add some memory overhead, but it should work.

**Comment by proteneer** [comment]
Thank you so much, I missed the SortPairs API.  Separating key/value pairs is not a problem, and is actually preferred. Closing this.
