### ISSUE TITLE
How to use cub::DeviceScan::InclusiveSum() to accumulate array in reverse order?

### ISSUE THREAD

**Issue by lanfeiying** [NVIDIA/cub#211]
Hi,
I have a question about how to use `cub::DeviceScan::InclusiveSum()` to accumulate an array in reverse order. I cannot find relevant material or tutorial online.   
For example: 
```
input:   1 1 0 0 1 0 1
```
After using `cub::DeviceScan::InclusiveSum()`, it will accumulate the input array in normal order (accumulate numbers from left to right):
```
normal output:  1 2 2 2 3 3 4
```
I want it to accumulate the input array in reverse order (accumulate numbers from right to left):
```
output in reverse order:  4 3 2 2 2 1 1
```
My question is how to do it?
I have read the documentation of this function, it says it supports customized iterator. 
I didn't find any tutorial about how to implement the iterator.
Could you give me any idea or suggestion? Thank you very much!

**Comment by elstehle** [comment]
Hi @lanfeiying,

just to ensure that I understand this correctly: you want to reverse the input, scan, and then reverse the scan's output order?
```
input:          1 1 0 0 1 0 1
reverse input:  1 0 1 0 0 1 1 
incl. scan:     1 1 2 2 2 3 4
reverse result: 4 3 2 2 2 1 1
```

Here is an example that does just that using thrust's [reverse_iterator](https://thrust.github.io/doc/classthrust_1_1reverse__iterator.html). 

Basically we did what is described above, just that, instead of writing the reversed input and output, we use the "fancy iterators" to avoid extra materialisation.


```C++
#include "cub/cub.cuh"
#include <thrust/iterator/reverse_iterator.h>

int main(int argc, char** argv)
{
  int v[] = {1, 1, 0, 0, 1, 0, 1};
  size_t num_items = sizeof(v)/sizeof(v[0]);
  int *d_v = nullptr;
  int *d_scan_out = nullptr;

  // cub temp storage
  void *d_temp_storage = nullptr;
  size_t temp_storage_bytes = 0;
  cub::DeviceScan::InclusiveSum(d_temp_storage, temp_storage_bytes, _rev_v, d_rev_scan_out, num_items);

  // memory allocations
  cudaMalloc(&d_v, num_items * sizeof(*d_v));
  cudaMalloc(&d_scan_out, num_items * sizeof(*d_v));
  cudaMalloc(&d_temp_storage, temp_storage_bytes);

  // transfer input to GPU
  cudaMemcpy(d_v, v, num_items * sizeof(*d_v), cudaMemcpyHostToDevice);

  // get an iterator that reverses the order of the input (pay attention that it begins at one-past-the-last item of d_b)
  auto d_rev_v = thrust::make_reverse_iterator(d_v + num_items);

  // get an iterator that reverses the order of the output
  auto d_rev_scan_out = thrust::make_reverse_iterator(d_scan_out + num_items);

  // Run exclusive prefix sum (watch how we pass the "fancy iterators" we created above for reverting the order)
  cub::DeviceScan::InclusiveSum(d_temp_storage, temp_storage_bytes, d_rev_v, d_rev_scan_out, num_items);

  // copy back the result
  cudaMemcpy(&v, d_scan_out, num_items * sizeof(*d_v), cudaMemcpyDeviceToHost);  

  for(int i=0; i<num_items; i++)
    std::cout << i << ": " << v[i] << "\n";
}
```

Hope this helps. Let me know if you have further questions.

**Comment by lanfeiying** [comment]
Hi, @elstehle ,
Thank you very much for your help! That is exactly what I want!
