### ISSUE TITLE
Allow segmented problems to have different types for offset iterator

### ISSUE THREAD

**Issue by devavret** [NVIDIA/cub#229]
Segmented reduce uses the same template type `OffsetIteratorT` for begin and end offsets
```c++
static CUB_RUNTIME_FUNCTION cudaError_t cub::DeviceSegmentedReduce::Sum
    (   void *              d_temp_storage,
        size_t &            temp_storage_bytes,
        InputIteratorT      d_in,
        OutputIteratorT     d_out,
        int                 num_segments,
        OffsetIteratorT     d_begin_offsets,  ///<<<
        OffsetIteratorT     d_end_offsets,    ///<<<
        cudaStream_t        stream = 0,
        bool                debug_synchronous = false 
    )
```
This precludes use of thrust transform iterators to generate the offsets. The implementation suggests that the iterators are only dereferenced to get the begin and end iterators independently per-block and as long as the dereferenced value is the same type, it should be ok for the iterators to be a different type.

Check the attached src for and example use case.
[cub_segment_repro.cu.zip](https://github.com/NVIDIA/cub/files/5457712/cub_segment_repro.cu.zip)

**Comment by psvvsp** [comment]
Tried to open the attached src on my windows machine but it appears to be empty.

**Comment by devavret** [comment]
I don't know how this happened. Here's a new one: 

[cub_segment_repro.cu.zip](https://github.com/NVIDIA/cub/files/6354169/cub_segment_repro.cu.zip)
