### ISSUE TITLE
Does DeviceSelect::Flagged allow flags which are neither 0 nor 1 ?

### ISSUE THREAD

**Issue by fkallen** [NVIDIA/cub#235]
The documentation of DeviceSelect::Flagged states "The value type of d_flags must be castable to bool (e.g., bool, char, int, etc.)." without further restrictions. https://nvlabs.github.io/cub/structcub_1_1_device_select.html#ad1273ce1f20e442c5a045e0fa17fd5fb

With items to select given by cub::CountingInputIterator<int>(0), 
running DeviceSelect::Flagged with flags {0,1,2,...,15} runs without errors. Running it with flags {0,1,2,...,16} causes "Invalid __global__write of size 4" (or __shared__ depending on flags).

See this example code: [main.zip](https://github.com/NVIDIA/cub/files/5516881/main.zip)

**Comment by allisonvacanti** [comment]
This isn't an issue with CUB - you're brushing up against a nasty corner of C++ that hides undefined behavior.

In C++, manipulating the underlying bit representation of `bool`s is undefined behavior, since `bool`'s representation is implementation dependent. Since this example is using `cudaMemcpy` to copy bits into a buffer of `bool`, the program is invalid. These sorts of issues can happen with [pure C++ code, too](https://twitter.com/shafikyaghmour/status/1152255305754873858).

The example code runs without errors if the `char` flag array is copied (with `std::copy` or similar, not `memcpy`) to a host buffer of bools before being transferred to the device.

Copying the repro case here:

```
#include <cub/cub.cuh>

#include <cassert>
#include <vector>
#include <numeric>
#include <iostream>

int main(){

    std::cout << "Running with cub version " << CUB_VERSION << "\n";

    for(int N = 0; N < 10000; N++){

        std::vector<char> flags(N);
        std::iota(flags.begin(), flags.end(), 0);

        bool* d_flags;
        cudaMalloc(&d_flags, N);
        cudaMemcpy(d_flags, flags.data(), N, cudaMemcpyHostToDevice);


        int* d_selected;
        cudaMalloc(&d_selected, sizeof(int) * N);

        int* d_numSelected;
        cudaMalloc(&d_numSelected, sizeof(int));

        cudaStream_t stream;
        cudaStreamCreate(&stream);

        assert(cudaSuccess == cudaGetLastError());

        std::size_t tempsize = 0;

        cub::DeviceSelect::Flagged(
            nullptr,
            tempsize,
            cub::CountingInputIterator<int>(0),
            d_flags,
            d_selected,
            d_numSelected,
            N,
            stream
        );

        char* d_temp;
        cudaMalloc(&d_temp, tempsize);

        cudaError_t status = cudaSuccess;
        
        status = cub::DeviceSelect::Flagged(
            d_temp,
            tempsize,
            cub::CountingInputIterator<int>(0),
            d_flags,
            d_selected,
            d_numSelected,
            N,
            stream
        );

        if(status != cudaSuccess){
            std::cerr << "error launch\n";
            std::cerr << "N = " << N << "\n";
            break;
        }else{
            //std::cerr << "ok launch\n";
        }

        status = cudaStreamSynchronize(stream); 
        if(status != cudaSuccess){
            std::cerr << "error execution\n";
            std::cerr << "N = " << N << "\n";
            break;
        }else{
            //std::cerr << "ok execution\n";
        }

        cudaFree(d_flags);
        cudaFree(d_selected);
        cudaFree(d_numSelected);
        cudaFree(d_temp);
        cudaStreamDestroy(stream);
    }
}
```

**Comment by allisonvacanti** [comment]
Additional info: 

The quick test I ran to confirm this changed

```
        std::vector<char> flags(N);
        std::iota(flags.begin(), flags.end(), 0);

        bool* d_flags;
        cudaMalloc(&d_flags, N);
        cudaMemcpy(d_flags, flags.data(), N, cudaMemcpyHostToDevice);
```

to

```
    std::vector<char> flags(N);
    std::iota(flags.begin(), flags.end(), 0);

    bool flags_bool[10000];
    std::copy(flags.cbegin(), flags.cend(), flags_bool);

    bool* d_flags;
    cudaMalloc(&d_flags, N);
    cudaMemcpy(d_flags, flags_bool, N, cudaMemcpyHostToDevice);
```

**Comment by fkallen** [comment]
Thank you for pointing this error out to me. 

However, if I use your suggested code and change the flag type from bool to int, I can observe the same error. Which brings me back to wondering whether it is allowed to use flags which have a value greater than 1 for this algorithm (assuming cub treats all values >= 1) as "true", or if I have to do the conversion beforehand ( for example using a TransformIterator which does the job)

```
        std::vector<int> flags(N);
        std::iota(flags.begin(), flags.end(), 0);

        int flags_temp[10000];
        std::copy(flags.cbegin(), flags.cend(), flags_temp);

        int* d_flags;
        cudaMalloc(&d_flags, N);
        cudaMemcpy(d_flags, flags_temp, N, cudaMemcpyHostToDevice);
```

**Comment by fkallen** [comment]
Thank you for pointing out this error to me. 

However, if I use your suggested code and change the flag type from bool to int, I can observe the same error. 

```
	std::vector<int> flags(N);
	std::iota(flags.begin(), flags.end(), 0);

	int flags_temp[10000];
	std::copy(flags.cbegin(), flags.cend(), flags_temp);

	int* d_flags;
	cudaMalloc(&d_flags, N * sizeof(int));
	cudaMemcpy(d_flags, flags_temp, N * sizeof(int), cudaMemcpyHostToDevice);
```

After looking at cub's implementation, I concluded that flags must have a numerical value of either 0 or 1, where items with flag 1 are selected. (Could this be a problem for bool flags if bool's representation is implementation depedent?)
It must be either 0 or 1, because flags are copied into the selection_flags buffer unconditionally. Afterwards, ExclusiveSum is used on selection_flags to find the positions of the selected elements.
If the numeric values of input flags are greater than 1, elements in the prefix sum buffer may point to invalid memory locations.

**Comment by allisonvacanti** [comment]
Thanks for investigating further. That is definitely a bug, I'll reopen this. We should be normalizing those flags at some point.
