### ISSUE TITLE
What operations can be done in-place?

### ISSUE THREAD

**Issue by HueHue44** [NVIDIA/cub#238]
Hello! I was just wondering which available operations can be done in-place (using the same iterator as input and output)? Specifically for `DeviceScan`and `DeviceSelect`. It is not clear in the documentation whether this is never allowed, always allowed or sometimes allowed. So does anyone know if there is some strict ruling on everything? Otherwise, I would like to know how it works specifically for `DeviceScan`and `DeviceSelect`.

**Comment by allisonvacanti** [comment]
`DeviceScan` can be run in-place, since each block will only read/write the portion of the input it is assigned.

I'm not sure about `DeviceSelect` -- from looking at the implementation it appears that there may be race conditions if run in-place, though I'd need to dig in a bit more to be absolutely sure. For now, I'd avoid running `DeviceSelect` in place.

We should check this for each algorithm and update the documentation at some point.

**Comment by HueHue44** [comment]
Alrighty, good to know that the scan can be run in palace. I'll be on the safe with `DeviceSelect` for now then. Thanks for the info!

**Comment by benbarsdell** [comment]
I'm also interested in this (specifically for `DeviceRadixSort`). In addition to documentation, a runtime error check (at least an assertion) in cases where it's not supported would be valuable.

**Comment by allisonvacanti** [comment]
@senior-zero since this came up in our call today, can you add this information while you're going through the CUB device algorithms?

**Comment by senior-zero** [comment]
Hello @HueHue44, @benbarsdell! I've created a series of PR that addresses in-place guarantees for various algorithms. Please, take a look at:
- partition [PR](https://github.com/NVIDIA/cub/pull/495)
- sort [PR](https://github.com/NVIDIA/cub/pull/499)
- reduce [PR](https://github.com/NVIDIA/cub/pull/500)
- rle [PR](https://github.com/NVIDIA/cub/pull/501)
- select [PR](https://github.com/NVIDIA/cub/pull/503)
- histogram [PR](https://github.com/NVIDIA/cub/pull/494)
- adjacent difference [PR](https://github.com/NVIDIA/cub/pull/492)
- scan [PR](https://github.com/NVIDIA/cub/pull/490)

**Comment by senior-zero** [comment]
All of the mentioned PRs were merged, closing the issue. Let us know if there is any algorithm without document its in-place guarantees.
