### ISSUE TITLE
warning: loop not unrolled in dispatch_radix_sort.cuh

### ISSUE THREAD

**Issue by andrewcorrigan** [NVIDIA/cub#246]
The latest version of CUB used by Thrust is triggering warnings in Clang:
```
/thrust/cub/device/dispatch/dispatch_radix_sort.cuh:521:1: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
DeviceRadixSortHistogramKernel
^
/thrust/cub/device/dispatch/dispatch_radix_sort.cuh:539:1: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
DeviceRadixSortOnesweepKernel
```

**Comment by andrewcorrigan** [comment]
I don't understand this code well enough to know if this is innocuous and safely ignored or if it needs to be fixed properly.  For now, I have suppressed the warning in my local copy.  If you're interested in a PR like the below, please let me know, and I will submit it.  Thanks!

```
#include <thrust/system/cuda/detail/core/triple_chevron_launch.h>

#if defined(__clang__)
#  pragma clang diagnostic push
#  pragma clang diagnostic ignored "-Wpass-failed"
#endif

/// Optional outer namespace(s)
CUB_NS_PREFIX
```

```
CUB_NS_POSTFIX  // Optional outer namespace(s)


#if defined(__clang__)
#  pragma clang diagnostic pop
#endif
```

**Comment by allisonvacanti** [comment]
The unrolls are purely for performance on old hardware/compilers, these warnings can be safely ignored.

This is related to NVIDIA/thrust#1344, which points out that a lot of these explicit unroll directives are actually hurting performance in some instances, and definitely aren't worth the extra compiler costs. I'm hoping to address that in the 1.13 / 1.14 timeframe, which will likely resolve this issue as well.

**Comment by andrewcorrigan** [comment]
Thank you for the explanation.  Since this can be safely ignored, I'm going to add the suppression code I posted above to my current PR, in case you're interested in merging that.

**Comment by canonizer** [comment]
@andrewcorrigan Do we know for which particular loop the warning is generated? There are no loops in the code of the kernel function itself, all loops are in the agent functions.

I'm asking because this warning is generated for the code I've written.

**Comment by andrewcorrigan** [comment]
Sorry.  I'm just a naive Thrust user.  All I know is what is in the warning messages posted at the top.  I'm not at all familiar with the internals.

**Comment by canonizer** [comment]
What compiler are you using that produces these warnings?

**Comment by andrewcorrigan** [comment]
I'm using Clang 11.  The warnings appear to be independent of CUDA toolkit version.
