### ISSUE TITLE
Take C++ dialect out of the name of built CUB examples/tests

### ISSUE THREAD

**Issue by brycelelbach** [NVIDIA/cub#250]
Always having the C++ dialect in the CUB test name (e.g. `cub.cpp14.test.device_select_unique.minimal`) is going to be problematic for testing NVC++ with CUB in the NVC++ test system. Can we fix this? Thrust doesn't do this when multi-config is off. I'd like that behavior.

I'd like to get the CUB tests turned on in NVC++'s test system ASAP so if we can prioritize this it would be great.

**Comment by allisonvacanti** [comment]
I was actually planning to implement CUB's behavior in Thrust as part of NVIDIA/thrust#1333 -- keep the info in the test / example executable names and just have the one path through the build system to maintain. Configuring for a single config would still be possible (and default to cpp.cuda.cpp14), but the info would stay in the test / executable names.

Can you explain how this breaks nvc++builds? It sounds like I'll need to rethink my plans for thrust.

**Comment by brycelelbach** [comment]
The NVC++ QA system wants to be able to pass through arbitrary flags to the compiler, which is how they manage configs for things like language dialect. Everything is just a flag for them.

We could just have an option to exclude it from the config name specifically for them.
