### ISSUE TITLE
Record version info in CMakeList.txt

### ISSUE THREAD

**Issue by jgbradley1** [NVIDIA/cub#253]
For better integration into CMake, the version number should be declared in the [`project()`](https://github.com/NVIDIA/cub/blob/main/CMakeLists.txt#L12) definition of the top-level CMakeList.txt.

For example
```
project(CUB 1.11.0)
```

This would automatically set a `CUB_VERSION` cmake variable for users to reference.

**Comment by allisonvacanti** [comment]
`CUB_VERSION` is already set through a different mechanism that allows us to only maintain a single version number location across the project.

Are you encountering a situation where this variable is not set in a downstream project?

**Comment by allisonvacanti** [comment]
Closing since this isn't really a problem as far as I'm aware. Feel free to reopen if this is causing issues for your project.
