### ISSUE TITLE
Potential Bug in the Down function of  cub/cub/block/block_shuffle.cuh 

### ISSUE THREAD

**Issue by sankarmanoj** [NVIDIA/cub#264]
The [Down](https://github.com/NVIDIA/cub/blob/main/cub/block/block_shuffle.cuh#L264) function looks like a copy of the `Up` function, without any changes. 

It should look something like this instead:
```
    template <int ITEMS_PER_THREAD>
    __device__ __forceinline__ void Down(
        T (&input)[ITEMS_PER_THREAD],
        T (&next)[ITEMS_PER_THREAD])  
    {
        temp_storage[linear_tid].next = input[0];

        CTA_SYNC();

        #pragma unroll
        for (int ITEM = 0; ITEM < (ITEMS_PER_THREAD - 1); ++ITEM)
            next[ITEM] = input[ITEM - 1];

        if (linear_tid <(BLOCK_THREADS -1))
            next[0] = temp_storage[linear_tid + 1].next;
    }
```

Also, the Up function was called where the Down function should have been called in cub/cub/block/block_shuffle.cuh:295

**Comment by allisonvacanti** [comment]
Thanks for letting us know -- this definitely needs to be fixed.
