### ISSUE TITLE
Comments typo

### ISSUE THREAD

**Issue by Peter9606** [NVIDIA/cub#271]
The blow two comments should exchange.

https://github.com/NVIDIA/cub/blob/499a7bad3416fcc71a7c50351d6b3cdbf3fbbc27/cub/util_type.cuh#L63-L70

https://github.com/NVIDIA/cub/blob/499a7bad3416fcc71a7c50351d6b3cdbf3fbbc27/cub/util_type.cuh#L90-L100

**Comment by rukshan99** [comment]
Can I work on this?

**Comment by allisonvacanti** [comment]
Absolutely!
