### ISSUE TITLE
Abstraction for Compute 8.0 warp reduce functions in CUB

### ISSUE THREAD

**Issue by pb-dseifert** [NVIDIA/cub#279]
Hi Nvidia,
first, CUB has been a great library and has helped me achieve peak performance in my CUDA programs. Going forward, I'd like to use the warp reduction intrinsics introduced with Ampere. OTOH, I also need to keep my programs compatible with Pascal at a minimum, so getting the equivalents of `cub::WarpReduce::Sum()` for `__reduce_add_sync`, `__reduce_min_sync`, `__reduce_max_sync`, `__reduce_and_sync`, `__reduce_or_sync` and `__reduce_xor_sync`. While I could resort to `cub::WarpReduce::Reduce(T input, ReductionOp reduction_op)` for these, I doubt I would get the peak performance because `nvcc` is unlikely to optimize this whole bunch of code down into `__reduce_foo` when targetting Ampere. Is this a reasonable request?

**Comment by allisonvacanti** [comment]
Thanks for the request.

This is something we are planning to look into. There is a lot of higher priority work to get through first, but exposing Ampere features through is high on our list.
