### ISSUE TITLE
Allow lambda functions to represent input and output instead of iterators

### ISSUE THREAD

**Issue by maxpkatz** [NVIDIA/cub#281]
When the input and output to an operation such as device-wide scan are represented by iterators, this maps well to the use case where the input and output are actual arrays that we are reading from and storing to. However, there are [other use cases](https://github.com/WeiqunZhang/amrex-random/blob/main/scan_lambda/main.cpp) where the input data may be computed entirely on the fly, or we may want to pre-process the input data before it is handed off to the scan, and where the output data may be directly consumed on the fly, or post-processed before it is stored in an output array. For those use cases we currently have to use separate arrays for the input and output, which may necessitate a round-trip to and from global memory for the input and/or the output as we first compute the data and then use it later.

If the input and output could additionally be represented by lambdas, the common use case could still be done (where for example the input lambda is basically `[=] (int i) { return input[i]; }`) but more complicated patterns could be expressed without sacrificing performance.

**Comment by jrhemstad** [comment]
This is precisely what [`thrust::transform_iterator`](https://thrust.github.io/doc/classthrust_1_1transform__iterator.html) and [`thrust::transform_output_iterator`](https://thrust.github.io/doc/classthrust_1_1transform__output__iterator.html) are for. These can be used in device code and interchangeably with CUB algorithms.

**Comment by allisonvacanti** [comment]
Closing -- Jake is correct, Thrust's transform iterators should be used.
