### ISSUE TITLE
Document that cub::DeviceRadixSort and cub::BlockRadixSort are stable

### ISSUE THREAD

**Issue by zasdfgbnm** [NVIDIA/cub#282]
There is nothing in the documentation https://nvlabs.github.io/cub/structcub_1_1_device_radix_sort.html saying whether it is stable sort or not. It seems to be stable. If so, it would be great if this fact is mentioned in the documentation.

**Comment by allisonvacanti** [comment]
Agreed. For the record, it is stable.

We're revamping the documentation page right now, we should update the docs to mention this soon.

**Comment by himanshu007-creator** [comment]
HI! i would like to work on this issue!

**Comment by allisonvacanti** [comment]
Sounds great! I'll assign it to you, just make a pull request with the updated docs when you have it ready.

Thanks!

**Comment by himanshu007-creator** [comment]
@allisonvacanti , can you help me locate the file please?

**Comment by allisonvacanti** [comment]
@himanshu007-creator Sure -- you'll just need to update this line:

https://github.com/NVIDIA/cub/blob/main/cub/device/device_radix_sort.cuh#L69

Before:

```
For floating-point types...
```

After:

```
This radix sort implementation is stable, and for floating-point types...
```

**Comment by zasdfgbnm** [comment]
Could we also add documentation for `cub::BlockRadixSort` and `cub::DeviceSegmentedRadixSort`?

**Comment by zasdfgbnm** [comment]
ping @allisonvacanti Are `cub::BlockRadixSort` and `cub::DeviceSegmentedRadixSort` stable?

**Comment by allisonvacanti** [comment]
Yes, the block radix sorts are stable. We should update the docs for this -- @himanshu007-creator could you update #284 and add the same docstring to the `cub::BlockRadixSort::Sort*` functions too?

https://github.com/NVIDIA/cub/blob/main/cub/block/block_radix_sort.cuh#L477

All of the functions following this one should be documented as stable.

**Comment by zasdfgbnm** [comment]
How about `cub::DeviceSegmentedRadixSort`? I assume it is stable as well.

**Comment by allisonvacanti** [comment]
Yes, all of the radix sorts are inherently stable -- let me know if you spot any others that I've missed, but I think that's all of them 😅

@himanshu007-creator the Sort* functions in https://github.com/NVIDIA/cub/blob/main/cub/device/device_segmented_radix_sort.cuh should also have the stability docstring in #284.
