### ISSUE TITLE
[RFE] Add merge sort support

### ISSUE THREAD

**Issue by zasdfgbnm** [NVIDIA/cub#283]
We are migrating `thrust::sort` to `cub::DeviceRadixSort` in PyTorch. We observe that, for small problem sizes, merge sort in thrust is much faster than cub's radix sort. See, for example, https://github.com/pytorch/pytorch/pull/55693

I suggest adding merge sort as a feature of cub, so that we can choose which sort to use.

**Comment by allisonvacanti** [comment]
This has been on my todo-list for a while.

Once we start expanding CUB's device algorithm library, merge sort will be among the first to be added.
