### ISSUE TITLE
cub::DeviceSpmv needs attention

### ISSUE THREAD

**Issue by allisonvacanti** [NVIDIA/cub#285]
This algorithm has no tests or examples, and some of the names look like they're from a work-in-progress (eg: `dispatch_spmv_orig.cuh`). We'll need to either deprecate and remove this code, or fix it up (there are a few bugs filed for it) and add tests/examples. 

If anyone is actively using this and would be impacted by its removal, leave a comment and let us know.

**Comment by leofang** [comment]
CuPy currently disables CUB SpMV if it's from CUDA's bundle, so it should not affect us if you decide to remove 🙂

**Comment by jdwapman** [comment]
I'd like to use CUB's SPMV as an analysis tool for the memory access patterns of merge-path-based SPMV, since original repo from Duane's paper is no longer compatible with the latest versions of CUDA.

**Comment by allisonvacanti** [comment]
Just to close the loop on this -- we're going to continue supporting it. #352 fixes some bugs and adds tests.
