### ISSUE TITLE
Update `DeviceSegmentedReduce` documentation to provide run-to-run guarantee.

### ISSUE THREAD

**Issue by allisonvacanti** [NVIDIA/cub#289]
`DeviceSegmentedReduce` reduces each segment using the same kernel as `DeviceReduce`, and thus provides the same run-to-run consistency guarantee for non-associative types. The documentation for `DeviceSegmentedReduce` should be updated to reflect this.

E.g. this bit: https://github.com/NVIDIA/cub/blob/a8910accebe74ce043a13026f8e71d678cddd6c1/cub/device/device_reduce.cuh#L91-L95
needs to be added to here: https://github.com/NVIDIA/cub/blob/a8910accebe74ce043a13026f8e71d678cddd6c1/cub/device/device_segmented_reduce.cuh#L72

**Comment by himanshu007-creator** [comment]
I would like to work on this issue🙂

**Comment by allisonvacanti** [comment]
Thanks! It's all yours :)
