### ISSUE TITLE
Document radix sort bitwise transformations on signed and floating-point types

### ISSUE THREAD

**Issue by zasdfgbnm** [NVIDIA/cub#293]
The highest bit in signed integers is the sign bit. If I use `end_bit` < `sizeof(KeyT)*8`, cub will not consider sign bits. And I suggest cub to clearly document this fact.

The confusing part of this problem is, for example, if I am using `KeyT = int64_t` to sort `[0, 1, 2, 3]`, I can use `end_bit=2` to speed up the sorting (PyTorch uses `end_bit` to speedup sorting in many places). But if the keys are `[0, 1, -1]` and `end_bit=2`, I don't know whether cub will use some trick to make sure `-1 < 0`, or will just do the same bit transformation as if `end_bit=32`. The experiment shows me that it is the latter, but I prefer this to be documented so that we know this is defined behavior.

A C++ program to demonstrate this problem is:

```CUDA
#include <iostream>
#include <cub/cub.cuh>
#include <cmath>

constexpr size_t N = 10;
using type = int64_t;
using value_type = long;

template<typename T>
void print(T array[], size_t N) {
    for(size_t i = 0; i < N; i++) {
        std::cout << float(array[i]) << ", ";
    }
    std::cout << std::endl;
}

int main() {
    type *h1, *h2, *d1, *d2;
    value_type *d3, *d4;
    void *tmp;
    h1 = new type[N];
    h2 = new type[N];
    for(size_t i = 0; i < N; i++) {
        h1[i] = -i;
    }
    print(h1, N);

    cudaMalloc(&d1, sizeof(type) * N);
    cudaMalloc(&d2, sizeof(type) * N);
    cudaMalloc(&d3, sizeof(value_type) * N);
    cudaMalloc(&d4, sizeof(value_type) * N);
    cudaMemcpy(d1, h1, sizeof(type) * N, cudaMemcpyDefault);
    size_t temp_storage_bytes;
    cub::DeviceRadixSort::SortPairs(nullptr, temp_storage_bytes, d1, d2, d3, d4, N, 0, 10);
    cudaMalloc(&tmp, temp_storage_bytes);
    cudaDeviceSynchronize();
    cub::DeviceRadixSort::SortPairs(tmp, temp_storage_bytes, d1, d2, d3, d4, N, 0, 10);
    cudaDeviceSynchronize();
    cudaMemcpy(h2, d2, sizeof(type) * N, cudaMemcpyDefault);
    print(h2, N);
}
```

From the above program, we can see that
```
[0, -1, -2, -3, -4, -5, -6, -7, -8, -9,]
```
is sorted to
```
[0, -9, -8, -7, -6, -5, -4, -3, -2, -1,]
```

**Comment by zasdfgbnm** [comment]
cc @ngimel

**Comment by allisonvacanti** [comment]
I agree, we should clarify how the bit transformations and the bit-range masking interact.

**Comment by illava** [comment]
> I agree, we should clarify how the bit transformations and the bit-range masking interact.

And sorting int from 0 to 32 bits seems producing unordered result? In my intuition it'd be treated as `unsigned int` and sorted as, is it also due to the interact of bit transformations and the bit-range masking?

`cub::DeviceRadixSort::SortKeys<int>(d_temp_storage, temp_storage_bytes, d_data, d_result, n, 0, 8 * sizeof(int));`

And also is `cudaStream_t stream = 0;` forbidden, which cause all result to 0?

```cpp
// file radix_sort.cu

#include <stdlib.h>
#include <stdio.h>
#include <iostream>
#include <algorithm>

#include <cuda_runtime.h>

#include <cub/device/device_radix_sort.cuh>

using T = int;
const int n = 3000;

template <typename T>
void device_sort(T *d_data, T *d_result, int n)
{
  void *d_temp_storage;
  size_t temp_storage_bytes;

  int begin_bit = 0;
  int end_bit = sizeof(T) * 8;
  cudaStream_t stream = 0;
  bool debug_synchronous = false;

#if 0
  cub::DeviceRadixSort::SortPairs<T, cub::NullType>(d_temp_storage, temp_storage_bytes, d_data, d_result, nullptr, nullptr, n, begin_bit, end_bit);
  cudaMalloc(&d_temp_storage, temp_storage_bytes);
  cub::DeviceRadixSort::SortPairs<T, cub::NullType>(d_temp_storage, temp_storage_bytes, d_data, d_result, nullptr, nullptr, n, begin_bit, end_bit);
#else
  cub::DeviceRadixSort::SortKeys<T>(d_temp_storage, temp_storage_bytes, d_data, d_result, n, begin_bit, end_bit);
  cudaMalloc(&d_temp_storage, temp_storage_bytes);
  cub::DeviceRadixSort::SortKeys<T>(d_temp_storage, temp_storage_bytes, d_data, d_result, n, begin_bit, end_bit);
#endif

  cudaFree(d_temp_storage);  
}

int main()
{
  size_t size = n * sizeof(T);

  T *h_data, *d_data, *d_result, *h_ref;
  h_data = (T *)malloc(size);
  h_ref = (T *)malloc(size);
  cudaMalloc(&d_data, size);
  cudaMalloc(&d_result, size);

  for (int i = 0; i < n; i++)
    h_data[i] = i * i * i * i * i * i;
  cudaMemcpy(d_data, h_data, size, cudaMemcpyHostToDevice);
  cudaMemcpy(h_ref, h_data, size, cudaMemcpyHostToHost);

  device_sort(d_data, d_result, n);

  cudaMemcpy(h_data, d_result, size, cudaMemcpyDeviceToHost);
  std::sort(h_ref, h_ref + n);
  for (int i = 0; i < std::min(n, 100); i++)
    std::cout << i << ": " << unsigned(h_data[i]) << " " << int(h_ref[i]) << std::endl;

  printf("Hello world!\n");
  free(h_data);
  free(h_ref);
  cudaFree(d_data);
  cudaFree(d_result);
}
```

```
.\a.exe
0: 0 -2147179191
1: 1 -2143908535
2: 64 -2143222967
3: 729 -2143027200
4: 4096 -2142623168
5: 15625 -2142551271
6: 46656 -2142167959
...
57: 4231676177 -2086404096
58: 3708954176 -2084306944
59: 3525827977 -2083261647
60: 3706327040 -2080078911
61: 4275734105 -2079473967
62: 965660736 -2079052319
63: 2393960065 -2066847680
64: 0 -2065009647
65: 2404446593 -2061533343
66: 1049571392 -2058136512
...
```
`cuda 11.1 sm_35`

**Comment by allisonvacanti** [comment]
For another point of reference (and a potential workaround), it looks like this is a bug that only affects the old implementation of radix sort, but not the new onesweep version from @canonizer.

Andy's version is used when:

- CUB >= 1.11 (CUDA Toolkit >= 11.3)
- virtual PTX SM target >= sm_60
- `sizeof(KeyType)` >= 4

When I run the example repro with `main` while targeting `sm_35`, I see the same as the above. Changing to `sm60` gives correct results:

<details><summary>Output with onesweep sort</summary><pre>
0: 2147788105 -2147179191
1: 2151058761 -2143908535
2: 2151744329 -2143222967
3: 2151940096 -2143027200
4: 2152344128 -2142623168
5: 2152416025 -2142551271
6: 2152799337 -2142167959
7: 2156144704 -2138822592
8: 2157401521 -2137565775
9: 2158171712 -2136795584
10: 2159686489 -2135280807
11: 2162371648 -2132595648
12: 2163267136 -2131700160
13: 2163511296 -2131456000
14: 2164260864 -2130706432
15: 2164260864 -2130706432
16: 2164559872 -2130407424
17: 2166888953 -2128078343
18: 2168717312 -2126249984
19: 2169346112 -2125621184
20: 2171844593 -2123122703
21: 2172470553 -2122496743
22: 2174049425 -2120917871
23: 2174167104 -2120800192
24: 2174538816 -2120428480
25: 2175853737 -2119113559
26: 2176192512 -2118774784
27: 2176472505 -2118494791
28: 2176782336 -2118184960
29: 2177977408 -2116989888
30: 2180485120 -2114482176
31: 2181074944 -2113892352
32: 2181589937 -2113377359
33: 2181940889 -2113026407
34: 2182508977 -2112458319
35: 2182789817 -2112177479
36: 2183841753 -2111125543
37: 2187644393 -2107322903
38: 2189103104 -2105864192
39: 2189280737 -2105686559
40: 2189537217 -2105430079
41: 2190006848 -2104960448
42: 2191069248 -2103898048
43: 2191785984 -2103181312
44: 2193883136 -2101084160
45: 2194218393 -2100748903
46: 2196453721 -2098513575
47: 2199461089 -2095506207
48: 2199837113 -2095130183
49: 2200174592 -2094792704
50: 2201485273 -2093482023
51: 2202102848 -2092864448
52: 2202889792 -2092077504
53: 2204612705 -2090354591
54: 2205114865 -2089852431
55: 2207576128 -2087391168
56: 2208239401 -2086727895
57: 2208563200 -2086404096
58: 2210660352 -2084306944
59: 2211705649 -2083261647
60: 2214888385 -2080078911
61: 2215493329 -2079473967
62: 2215914977 -2079052319
63: 2228119616 -2066847680
64: 2229957649 -2065009647
65: 2233433953 -2061533343
66: 2236830784 -2058136512
67: 2237108224 -2057859072
68: 2237272064 -2057695232
69: 2237566976 -2057400320
70: 2240188416 -2054778880
71: 2240700697 -2054266599
72: 2241621056 -2053346240
73: 2243029056 -2051938240
74: 2243285193 -2051682103
75: 2244644864 -2050322432
76: 2244744793 -2050222503
77: 2245419584 -2049547712
78: 2247200768 -2047766528
79: 2247459073 -2047508223
80: 2248393561 -2046573735
81: 2250233001 -2044734295
82: 2250313728 -2044653568
83: 2252456512 -2042510784
84: 2252603392 -2042363904
85: 2253094473 -2041872823
86: 2253210409 -2041756887
87: 2253229489 -2041737807
88: 2255555136 -2039412160
89: 2256797696 -2038169600
90: 2257641024 -2037326272
91: 2258147377 -2036819919
92: 2259459449 -2035507847
93: 2259838528 -2035128768
94: 2260209664 -2034757632
95: 2260970489 -2033996807
96: 2261332032 -2033635264
97: 2261826905 -2033140391
98: 2262618633 -2032348663
99: 2262727033 -2032240263
Hello world!
</pre></details>

**Comment by allisonvacanti** [comment]
I opened #310 to track the bug separately from the documentation change.

**Comment by illava** [comment]
@allisonvacanti Reviewing my code I found the uninitialized code`  void *d_temp_storage = nullptr;` which seems solved the problem or `an illegal memory access was encountered`.
Thanks for the help, the code is correct.

**Comment by allisonvacanti** [comment]
@illava Ah, good catch, thanks for letting me know -- I missed that, too.

I'll close the other bug.
