### ISSUE TITLE
Variable Length Array Sorting and Reduce

### ISSUE THREAD

**Issue by YukeWang96** [NVIDIA/cub#327]
Hi,

Is there any support for using CUB for variable length array in sorting and reduce, the current example only consider very regular shape array, such as 128 threads each with 4 elements. 

> what if the array length is not divisible by thread per block? 
> what if the length of the array can only be determined at the runtime?

How should I do sorting and reduce by using CUB.

Thanks

**Comment by canonizer** [comment]
For block sorting, the only approach currently available is to fill the rest of the array with a "dummy" element, e.g. `INT_MAX` when sorting `int` in ascending order. After the sorting is finished, these elements should be at the end of the array, so you can ignore them. If the size of the array varies considerably, you can instantiate several versions of `cub::BlockRadixSort` with different values of `ITEMS_PER_THREAD`, and choose one based on the number of elements you have.

For reduction, you can use a similar approach and fill the rest of the array with the neutral element, e.g. 0 for summation. However, there is also a version of `Reduce()` that specifies how many threads contribute elements to the reduction: https://nvlabs.github.io/cub/classcub_1_1_block_reduce.html#a0e947f6a1d812d21839632b87aaf32e5.

**Comment by senior-zero** [comment]
Hello @YukeWang96! I'm currently working on a variable size radix sort for block scope which can work with arbitrary input size (even more than `ITEMS_PER_THREAD * BLOCK_THREADS`). Are you interested in this case or your input data size is always within `ITEMS_PER_THREAD * BLOCK_THREADS` limits?

**Comment by chenxuhao** [comment]
> After the sorting is fi

Hi @senior-zero I am super interested in sorting arbitrary input sizes. Is this available now?

**Comment by senior-zero** [comment]
Hello, @chenxuhao! The facility exists as an agent, not a block-scope API so the usage is a bit involved. Please, take a look at the following [comment](https://github.com/NVIDIA/cub/issues/292#issuecomment-905333004).

**Comment by chenxuhao** [comment]
> Hello, @chenxuhao! The facility exists as an agent, not a block-scope API so the usage is a bit involved. Please, take a look at the following [comment](https://github.com/NVIDIA/cub/issues/292#issuecomment-905333004).

Than you so much for the link. In oder to use this agent, I have to set the type SegmentedPolicyT or ChainedPolicyT, which I have no idea how to do. Is there any example that I can follow? Thanks.

**Comment by senior-zero** [comment]
@chenxuhao I don't think it's quite correct. Below is the fixed version. The double buffer is needed, currently there's no in-place version.

```cpp
#include <cub/cub.cuh>
#include <thrust/device_vector.h>
#include <thrust/sequence.h>
#include <thrust/sort.h>
#include <thrust/execution_policy.h>

#include <iostream>

template <int BlockThreads, class KeyT>
struct policy_t {
  constexpr static int BLOCK_THREADS = BlockThreads;
  constexpr static int RADIX_BITS = sizeof(KeyT) > 1 ? 6 : 4;

  using LargeSegmentPolicy =
    cub::AgentRadixSortDownsweepPolicy<BLOCK_THREADS,
                                       9,
                                       KeyT,
                                       cub::BLOCK_LOAD_TRANSPOSE,
                                       cub::LOAD_DEFAULT,
                                       cub::RADIX_RANK_MEMOIZE,
                                       cub::BLOCK_SCAN_WARP_SCANS,
                                       RADIX_BITS>;

  using SmallAndMediumSegmentedSortPolicyT =
    cub::AgentSmallAndMediumSegmentedSortPolicy<

      BLOCK_THREADS,

      // Small policy
      cub::AgentSubWarpMergeSortPolicy<4, // threads per problem
                                       5, // items per thread
                                       cub::WarpLoadAlgorithm::WARP_LOAD_DIRECT,
                                       cub::CacheLoadModifier::LOAD_DEFAULT>,

      // Medium policy
      cub::AgentSubWarpMergeSortPolicy<32, // threads per problem
                                       5,  // items per thread
                                       cub::WarpLoadAlgorithm::WARP_LOAD_DIRECT,
                                       cub::CacheLoadModifier::LOAD_DEFAULT>>;
};

template <int BlockThreads, class KeyT, class OffsetT>
inline __device__ void 
cta_sort(OffsetT num_items, cub::detail::device_double_buffer<KeyT> &keys) {
  if (num_items <= 0) {
    return;
  }

  using value_t = cub::NullType;
  using policy = policy_t<BlockThreads, KeyT>;
  using large_policy = typename policy::LargeSegmentPolicy;
  using medium_policy = typename policy::SmallAndMediumSegmentedSortPolicyT::MediumPolicyT;

  constexpr int radix_bits = large_policy::RADIX_BITS;
  constexpr bool is_descending = false;

  using warp_reduce_t = cub::WarpReduce<KeyT>;
  using agent_warp_merge_sort_t = cub::AgentSubWarpSort<is_descending, medium_policy, KeyT, value_t, OffsetT>;
  using agent_segmented_radix_sort_t = cub::AgentSegmentedRadixSort<is_descending, large_policy, KeyT, value_t, OffsetT>;

  __shared__ union {
    typename agent_segmented_radix_sort_t::TempStorage block_sort;
    typename agent_warp_merge_sort_t ::TempStorage medium_warp_sort;
  } temp_storage;

  agent_segmented_radix_sort_t agent(num_items, temp_storage.block_sort);

  constexpr int begin_bit = 0;
  constexpr int end_bit = sizeof(KeyT) * 8;
  constexpr int cacheable_tile_size = BlockThreads * large_policy::ITEMS_PER_THREAD;

  value_t *value_ptr = nullptr;

  if (num_items <= medium_policy::ITEMS_PER_TILE) {
    if (threadIdx.x < medium_policy::WARP_THREADS) {
      agent_warp_merge_sort_t(temp_storage.medium_warp_sort)
          .ProcessSegment(num_items, keys.current(), keys.alternate(), value_ptr, value_ptr);
      keys.swap();
    }
  } else if (num_items < cacheable_tile_size) {
    agent.ProcessSinglePass(begin_bit, end_bit, keys.current(), value_ptr, keys.alternate(), value_ptr);
    keys.swap();
  } else {
    int current_bit = begin_bit;
    int pass_bits = (cub::min)(int{radix_bits}, (end_bit - current_bit));
    agent.ProcessIterative(current_bit, pass_bits, keys.current(), value_ptr, keys.alternate(), value_ptr);
    keys.swap();

    current_bit += pass_bits;
    #pragma unroll 1
    while (current_bit < end_bit) {
      pass_bits = (cub::min)(int{radix_bits}, (end_bit - current_bit));
      cub::CTA_SYNC();
      agent.ProcessIterative(current_bit, pass_bits, keys.current(), value_ptr, keys.alternate(), value_ptr);
      keys.swap();
      current_bit += pass_bits;
    }
  }
}

template <int BlockThreads>
__global__ void kernel(int num_items, int *src, int *buffer, int** result) {
  cub::detail::device_double_buffer<int> keys(src, buffer);
  cta_sort<BlockThreads>(num_items, keys);
  *result = keys.current();
}

int main() {
  constexpr int block_threads = 256;

  thrust::device_vector<int*> result(1);
  int** d_result = thrust::raw_pointer_cast(result.data());

  for (int num_items = 1; num_items < 1024 * 1024; num_items *= 2) {
    thrust::device_vector<int> keys_source(num_items);
    thrust::device_vector<int> keys_buffer(num_items);

    int *d_keys_source = thrust::raw_pointer_cast(keys_source.data());
    int *d_keys_buffer = thrust::raw_pointer_cast(keys_buffer.data());

    thrust::sequence(keys_source.rbegin(), keys_source.rend());

    kernel<block_threads><<<1, block_threads>>>(num_items, d_keys_source, d_keys_buffer, d_result);

    int *h_result = result[0];

    if (thrust::is_sorted(thrust::device, h_result, h_result + num_items)) {
      std::cout << num_items << " ok" << std::endl;
    } else {
      std::cout << num_items << " fail" << std::endl;
    }
  }
}

```

**Comment by chenxuhao** [comment]
> @chenxuhao I don't think it's quite correct. Below is the fixed version. The double buffer is needed, currently there's no in-place version.
> 
> ```c++
> #include <cub/cub.cuh>
> #include <thrust/device_vector.h>
> #include <thrust/sequence.h>
> #include <thrust/sort.h>
> #include <thrust/execution_policy.h>
> 
> #include <iostream>
> 
> template <int BlockThreads, class KeyT>
> struct policy_t {
>   constexpr static int BLOCK_THREADS = BlockThreads;
>   constexpr static int RADIX_BITS = sizeof(KeyT) > 1 ? 6 : 4;
> 
>   using LargeSegmentPolicy =
>     cub::AgentRadixSortDownsweepPolicy<BLOCK_THREADS,
>                                        9,
>                                        KeyT,
>                                        cub::BLOCK_LOAD_TRANSPOSE,
>                                        cub::LOAD_DEFAULT,
>                                        cub::RADIX_RANK_MEMOIZE,
>                                        cub::BLOCK_SCAN_WARP_SCANS,
>                                        RADIX_BITS>;
> 
>   using SmallAndMediumSegmentedSortPolicyT =
>     cub::AgentSmallAndMediumSegmentedSortPolicy<
> 
>       BLOCK_THREADS,
> 
>       // Small policy
>       cub::AgentSubWarpMergeSortPolicy<4, // threads per problem
>                                        5, // items per thread
>                                        cub::WarpLoadAlgorithm::WARP_LOAD_DIRECT,
>                                        cub::CacheLoadModifier::LOAD_DEFAULT>,
> 
>       // Medium policy
>       cub::AgentSubWarpMergeSortPolicy<32, // threads per problem
>                                        5,  // items per thread
>                                        cub::WarpLoadAlgorithm::WARP_LOAD_DIRECT,
>                                        cub::CacheLoadModifier::LOAD_DEFAULT>>;
> };
> 
> template <int BlockThreads, class KeyT, class OffsetT>
> inline __device__ void 
> cta_sort(OffsetT num_items, cub::detail::device_double_buffer<KeyT> &keys) {
>   if (num_items <= 0) {
>     return;
>   }
> 
>   using value_t = cub::NullType;
>   using policy = policy_t<BlockThreads, KeyT>;
>   using large_policy = typename policy::LargeSegmentPolicy;
>   using medium_policy = typename policy::SmallAndMediumSegmentedSortPolicyT::MediumPolicyT;
> 
>   constexpr int radix_bits = large_policy::RADIX_BITS;
>   constexpr bool is_descending = false;
> 
>   using warp_reduce_t = cub::WarpReduce<KeyT>;
>   using agent_warp_merge_sort_t = cub::AgentSubWarpSort<is_descending, medium_policy, KeyT, value_t, OffsetT>;
>   using agent_segmented_radix_sort_t = cub::AgentSegmentedRadixSort<is_descending, large_policy, KeyT, value_t, OffsetT>;
> 
>   __shared__ union {
>     typename agent_segmented_radix_sort_t::TempStorage block_sort;
>     typename agent_warp_merge_sort_t ::TempStorage medium_warp_sort;
>   } temp_storage;
> 
>   agent_segmented_radix_sort_t agent(num_items, temp_storage.block_sort);
> 
>   constexpr int begin_bit = 0;
>   constexpr int end_bit = sizeof(KeyT) * 8;
>   constexpr int cacheable_tile_size = BlockThreads * large_policy::ITEMS_PER_THREAD;
> 
>   value_t *value_ptr = nullptr;
> 
>   if (num_items <= medium_policy::ITEMS_PER_TILE) {
>     if (threadIdx.x < medium_policy::WARP_THREADS) {
>       agent_warp_merge_sort_t(temp_storage.medium_warp_sort)
>           .ProcessSegment(num_items, keys.current(), keys.alternate(), value_ptr, value_ptr);
>       keys.swap();
>     }
>   } else if (num_items < cacheable_tile_size) {
>     agent.ProcessSinglePass(begin_bit, end_bit, keys.current(), value_ptr, keys.alternate(), value_ptr);
>     keys.swap();
>   } else {
>     int current_bit = begin_bit;
>     int pass_bits = (cub::min)(int{radix_bits}, (end_bit - current_bit));
>     agent.ProcessIterative(current_bit, pass_bits, keys.current(), value_ptr, keys.alternate(), value_ptr);
>     keys.swap();
> 
>     current_bit += pass_bits;
>     #pragma unroll 1
>     while (current_bit < end_bit) {
>       pass_bits = (cub::min)(int{radix_bits}, (end_bit - current_bit));
>       cub::CTA_SYNC();
>       agent.ProcessIterative(current_bit, pass_bits, keys.current(), value_ptr, keys.alternate(), value_ptr);
>       keys.swap();
>       current_bit += pass_bits;
>     }
>   }
> }
> 
> template <int BlockThreads>
> __global__ void kernel(int num_items, int *src, int *buffer, int** result) {
>   cub::detail::device_double_buffer<int> keys(src, buffer);
>   cta_sort<BlockThreads>(num_items, keys);
>   *result = keys.current();
> }
> 
> int main() {
>   constexpr int block_threads = 256;
> 
>   thrust::device_vector<int*> result(1);
>   int** d_result = thrust::raw_pointer_cast(result.data());
> 
>   for (int num_items = 1; num_items < 1024 * 1024; num_items *= 2) {
>     thrust::device_vector<int> keys_source(num_items);
>     thrust::device_vector<int> keys_buffer(num_items);
> 
>     int *d_keys_source = thrust::raw_pointer_cast(keys_source.data());
>     int *d_keys_buffer = thrust::raw_pointer_cast(keys_buffer.data());
> 
>     thrust::sequence(keys_source.rbegin(), keys_source.rend());
> 
>     kernel<block_threads><<<1, block_threads>>>(num_items, d_keys_source, d_keys_buffer, d_result);
> 
>     int *h_result = result[0];
> 
>     if (thrust::is_sorted(thrust::device, h_result, h_result + num_items)) {
>       std::cout << num_items << " ok" << std::endl;
>     } else {
>       std::cout << num_items << " fail" << std::endl;
>     }
>   }
> }
> ```

Thank you so much for the help. This works for me: https://github.com/chenxuhao/GraphAIBench/blob/0994186674e39443b39939c3d6356aa690052eb4/include/sort.cuh#L37

Also, I wonder if it is possible to create a similar routine like warp_sort which does warp-wise sorting instead of cta-wise?
