### ISSUE TITLE
CachingDeviceAllocator::DeviceFree problematic handling of non-live block pointer

### ISSUE THREAD

**Issue by mlfz** [NVIDIA/cub#329]
In the following code snippet:

https://github.com/NVIDIA/cub/blob/2200c6af27710264023314f1598c3ed1f46560cb/cub/util_allocator.cuh#L617-L625

`recahced` can be false due to the fact that `d_ptr` is not in `live_blocks`, when the earlier `live_blocks.find()` would fail.
- If it is in `cached_blocks`, this will free the the memory without updating `cached_blocks`, which can then be reassigned in future `DeviceAllocate`.
- If the search fail, `search_key.event` is 0, the cudaEventDestroy will return `cudaErrorInvalidResourceHandle`, which is quite unexpected.

This can happen, for example, when one accidentally double-free with `DeviceFree`.

**Comment by allisonvacanti** [comment]
Can you provide an example that reproduces this issue?

**Comment by mlfz** [comment]
> Can you provide an example that reproduces this issue?

```cpp
TEST(ThrustCubCachingDeviceAllocator, DoubleFree) {
  // Using via Thrust with -DTHRUST_CACHING_MALLOC
  using CubAllocator = thrust::cuda_cub::cub::CachineDeviceAllocator;
  CubAllocator & g_cub_allocator = thrust::cuda_cub::get_allocator(); 
  void *d_ptr;
  EXPECT_EQ(g_cub_allocator.DeviceAllocate(&d_ptr, 512), cudaSuccess);
  EXPECT_EQ(g_cub_allocator.DeviceFree(d_ptr), cudaSuccess); // fine, return to cached_block

  // double-deallocate
  cudaError_t error;
  error = g_cub_allocator.DeviceFree(d_ptr);
  EXPECT_EQ(error, cudaSuccess); // cudaFree(d_ptr) would have returned cudaErrorInvalidDevicePointer, but we got cudaErrorInvalidResourceHandle
  cudaGetLastError(); // clear runtime error

  // call cudaMemcpy to demonstrate that d_ptr is cudaFree'd
  char host[512];
  error = cudaMemcpy(host, d_ptr, 512, cudaMemcpyDeviceToHost);
  EXPECT_EQ(error, cudaErrorInvalidDevicePointer); // this assertion passes
  // but ptr is still assignable in cached_block:
  auto find_iter = std::find_if(
    g_cub_allocator.cached_blocks.begin(),
    g_cub_allocator.cached_blocks.end(),
    [&d_ptr](const CubAllocator::BlockDescriptor& block) { return block.d_ptr == d_ptr; });
  EXPECT_EQ(find_iter, g_cub_allocator.cached_blocks.end());
}
```

**Comment by brycelelbach** [comment]
I'd advise switching to Thrust's new memory resource based allocator system, which includes caching allocators and is way more robust.

**Comment by jrhemstad** [comment]
Double freeing a pointer is undefined behavior, which includes the behavior seen here.

**Comment by mlfz** [comment]
> Double freeing a pointer is undefined behavior, which includes the behavior seen here.

I agree. This is just to demonstrate the behavior when calling this allocator to deallocate a pointer that is not in its live block. I honestly don't know what should be the behavior when user calls `DeviceDeallocate` to deallocate a non-live pointer.  I recently found that CUDA-10. Thrust with `THRUST_CACHING_DEVICE_MALLOC` flag on can call `DeviceAllocate(nullptr)`, which returns `cudaErrorInvalidHandle`.

When the GPU is  out of memory, the allocation in Thrust does not throw when malloc failed and return a `nullptr`:
https://github.com/NVIDIA/thrust/blob/cuda-10.2/thrust/system/cuda/detail/malloc_and_free.h#L66
As a result, this clean up code in `thrust::device_vector` throws:
https://github.com/NVIDIA/thrust/blob/cuda-10.2/thrust/detail/vector_base.inl#L885
with an error message about cudaErrorInvalidHandle.

This is addressed in CUDA-11 Thrust, which throws an exception. So now at least user get notified at allocation time, rather than a seemingly unrelated CUDA error (from user's point of view, there is no CUDA handle involved) during deallocation.

**Comment by allisonvacanti** [comment]
Looks like this has been fixed. Closing.
