### ISSUE TITLE
Remove manual loop unrolling

### ISSUE THREAD

**Issue by senior-zero** [NVIDIA/cub#337]
At the moment, there's no benefit from manual loop unrolling with `struct Iterate`. We could simplify the code by using simple for loops with `#pragma unroll` in `cub::BlockDiscontinuity`. Preliminary tests of the mentioned modification in `cub::BlockAdjacentDifference` show that the generated PTX doesn't change.

**Comment by kshitij12345** [comment]
@senior-zero @allisonvacanti Is it ok if I give this a shot? Thanks!

**Comment by allisonvacanti** [comment]
@kshitij12345 Feel free to try it. It'll likely be a while until it's merged into `main` since we need to do more testing on it, but it should be usable.

**Comment by kshitij12345** [comment]
Sure. I'll give it a shot. Are there other issues that I can help with? I am interested in learning more and contributing to `cub`. Thanks!

**Comment by allisonvacanti** [comment]
I'm definitely interested in contributions!

Can you send me an email at `avacanti@nvidia.com` and let me know what sort of things you're interested in, and what your experience is with C++/CUDA? I'm sure I can find something for you to help out with, but I want to make sure it aligns with your skills/interests. Thanks!
