### ISSUE TITLE
cub::DeviceSegmentedReduce::Reduce  error

### ISSUE THREAD

**Issue by pkufool** [NVIDIA/cub#368]
I found an error when using `cub::DeviceSegmentedReduce::Reduce`, see the code below:
```
int32_t num_rows = row_splits_array.Dim() - 1;
const int32_t *row_splits = row_splits_array.Data();
argmax_internal::PairInputIterator<float> input_iter(values_data);
argmax_internal::PairOutputIterator<float> output_iter(output_data);
argmax_internal::PairMaxOp<float> op;
argmax_internal::Pair<float> initial_pair{initial_value, -1};

// This code is based on the example here:
// https://nvlabs.github.io/cub/structcub_1_1_device_segmented_reduce.html
std::size_t temp_storage_bytes = 0;

// the first time is to determine temporary device storage requirements
cub::DeviceSegmentedReduce::Reduce(
    nullptr, temp_storage_bytes, input_iter, output_iter, num_rows,
    row_splits, row_splits + 1, op, initial_pair, c->GetCudaStream()));
Array1<int8_t> d_temp_storage(c, temp_storage_bytes);
cub::DeviceSegmentedReduce::Reduce(
    d_temp_storage.Data(), temp_storage_bytes, input_iter, output_iter,
    num_rows, row_splits, row_splits + 1, op, initial_pair,
    c->GetCudaStream()));
```
I upload the bad case to (https://drive.google.com/drive/folders/1Bm4BHFzniAxCcnqHFPE3S3bccrriaJg5?usp=sharing), the value_data is the array in **values.txt** the row_splits_array is the array in **splits.txt** and the error result is in **error.txt**, the initial_value is **-inf**.

The error occurred in the second last sublist, the max value of the second last sublist should be the first one, but the output is the 42th. And I tried to construct some new test case by picking out some of these sublists(including the error one), the result was right. So, I thought it it not an error for particular data, it may be an error about number of the sublists, the result of the sublist in position i of n would be not right, especially the ones in the tail.

**Comment by csukuangfj** [comment]
@danpovey

The issue is reported here.  We are making an all-in-one `.cu` file for easy reproducing.

**Comment by pkufool** [comment]
There is a bug in our internal code, sorry!
