### ISSUE TITLE
cub::GridBarrier GPU hang issue

### ISSUE THREAD

**Issue by lilohuang** [NVIDIA/cub#369]
Hi cub experts,

The below example was modified from "cub/test/test_grid_barrier.cu" which demonstrates GPU hang (GPU busy waiting) issue on NVIDIA P100. The issue can be resolved if I change the grid_size to 56.

Is this issue related to https://github.com/NVIDIA/cub/issues/356 due to incorrect semantics?  Any idea or workaround would be appreciated.  @senior-zero  @allisonvacanti 

```cuda
#include <cub/grid/grid_barrier.cuh>

__global__ void foobar(cub::GridBarrier global_barrier, int iterations) {
   for (int i=0; i<iterations; i++) {
      global_barrier.Sync();
   }
}

int main() {

   int grid_size = 128;    // change to 56 can get rid of the GPU hang on P100.
   cub::GridBarrierLifetime global_barrier;
   global_barrier.Setup(grid_size);
   foobar<<<grid_size, 1024>>>(global_barrier, 8);
   CubDebug(cudaGetLastError());
   CubDebug(cudaDeviceSynchronize());

   return 0;
}
```

Thank you so much,
Lilo

**Comment by senior-zero** [comment]
Hello, @lilohuang!

This issue isn't related to #356. Your kernel hangs because your GPU can't sustain the requested number of thread blocks. The grid barrier requires that grid size doesn't exceed the maximal number of thread blocks that can work simultaneously. 


This behaviour can be explained as follows. The main thread block is spinning until the thread block `MAX + 1` reports that it's ready. The `MAX + 1`-th thread block won't be launched until there's a slot in a GPU. Other thread blocks won't release a slot in the GPU until the barrier isn't executed. Therefore we have a deadlock. Here's how you can fix this issue:

```cuda
#include <cub/grid/grid_barrier.cuh>
#include <iostream>

__global__ void foobar(cub::GridBarrier global_barrier, int iterations) {
    for (int i = 0; i < iterations; i++) {
        global_barrier.Sync();
    }
}

int main() {

    int max_sm_occupancy{};

    cudaOccupancyMaxActiveBlocksPerMultiprocessor(
            &max_sm_occupancy,
            foobar,
            1024 /* block threads */,
            0 /* dyn shared memory */);

    int sm_count{};
    cudaDeviceGetAttribute(&sm_count, cudaDevAttrMultiProcessorCount, 0 /* device id */);
    int grid_size = max_sm_occupancy * sm_count;

    std::cout << "Max thread blocks per SM: " << max_sm_occupancy << std::endl;
    std::cout << "#SM: " << sm_count << std::endl;

    cub::GridBarrierLifetime global_barrier;
    global_barrier.Setup(grid_size);
    foobar<<<grid_size, 1024>>>(global_barrier, 8);
    CubDebug(cudaGetLastError());
    CubDebug(cudaDeviceSynchronize());

    return 0;
}
```

**Comment by lilohuang** [comment]
Thanks @senior-zero  your strong support. It would be great if cub documentation can describe it clearly. :)

**Comment by senior-zero** [comment]
> Thanks @senior-zero your strong support. It would be great if cub documentation can describe it clearly. 🤣

Thank you for the comment! It's definitely worth mentioning in the documentation. Could you describe this request in the form of an issue?

**Comment by lilohuang** [comment]
@senior-zero  https://github.com/NVIDIA/cub/issues/371 has been created to follow up the issue, thanks again 👍
