### ISSUE TITLE
is WARP_BALLOT inside LookbackGlobal redundant?

### ISSUE THREAD

**Issue by chongxing** [NVIDIA/cub#412]
in file cub/agent/agent_radix_sort_onesweep.cuh

    __device__ __forceinline__ void LookbackGlobal(int (&bins)[BINS_PER_THREAD])
    {
        #pragma unroll
        for (int u = 0; u < BINS_PER_THREAD; ++u)
        {
            int bin = ThreadBin(u);
            if (FULL_BINS || bin < RADIX_DIGITS)
            {
                OffsetT inc_sum = bins[u];
                int want_mask = ~0;
                // backtrack as long as necessary
                for (OffsetT block_jdx = block_idx - 1; block_jdx >= 0; --block_jdx)
                {
                    // wait for some value to appear
                    OffsetT value_j = 0;
                    AtomicOffsetT& loc_j = d_lookback[block_jdx * RADIX_DIGITS + bin];
                    do {
                        __threadfence_block(); // prevent hoisting loads from loop
                        value_j = ThreadLoad<LOAD_VOLATILE>(&loc_j);
                    } while (value_j == 0);

                    inc_sum += value_j & LOOKBACK_VALUE_MASK;
                    want_mask = WARP_BALLOT((value_j & LOOKBACK_GLOBAL_MASK) == 0, want_mask);
                    if (value_j & LOOKBACK_GLOBAL_MASK) break;
                }
                AtomicOffsetT& loc_i = d_lookback[block_idx * RADIX_DIGITS + bin];
                OffsetT value_i = inc_sum | LOOKBACK_GLOBAL_MASK;
                ThreadStore<STORE_VOLATILE>(&loc_i, value_i);
                s.global_offsets[bin] += inc_sum - bins[u];
            }
        }
    }

I read the code, and find that
What's the purpose of this statement “want_mask = WARP_BALLOT((value_j & LOOKBACK_GLOBAL_MASK) == 0, want_mask);” 
want_mask is not used besides this statement itself.
IMHO, It looks redundant. Any special consideration? or just happen to be there.

**Comment by allisonvacanti** [comment]
@canonizer Can you take a look at this?

**Comment by canonizer** [comment]
It's definitely redundant from the functional perspective. However, leaving it out does have a small but noticeable effect on performance. That's why it is there.

The same applies to the `WARP_BALLOT()` when writing out the items to global memory, see https://github.com/NVIDIA/cub/blob/main/cub/agent/agent_radix_sort_onesweep.cuh#L479.

**Comment by chongxing** [comment]
> cub/agent/agent_radix_sort_onesweep.cuh

@canonizer  Oh, it might be divergent when leaving above "while (value_j == 0)" loop, so this WARP_BALLOT makes it reconverge. I see. Thanks very much.
