### ISSUE TITLE
Documentation for `cub::DeviceSpmv` refers to unused `alpha` and `beta` parameters

### ISSUE THREAD

**Issue by WeiqunZhang** [NVIDIA/cub#416]
There is some inconsistency in the documentation for `cub::DeviceSpmv` (https://nvlabs.github.io/cub/structcub_1_1_device_spmv.html).  The overview says
```
The SpMV computation performs the matrix-vector operation y = alpha*A*x + beta*y,
```
But the function signature of `CsrMV` has neither `alpha` nor `beta`, and the function's description says
```
This function performs the matrix-vector operation y = A*x
```
However, the code snippet has `alpha` and `beta`.
```
cub::DeviceSpmv::CsrMV(d_temp_storage, temp_storage_bytes, d_values,
    d_row_offsets, d_column_indices, d_vector_x, d_vector_y,
    num_rows, num_cols, num_nonzeros, alpha, beta);
```
Could someone clarify on this?  Thanks!

**Comment by allisonvacanti** [comment]
Thanks for reporting this! This should be fixed for the next release.

You are correct, the DeviceSPMV function does not expose the alpha/beta parameters, they are fixed to 1 and 0 respectively.
