### ISSUE TITLE
Compilation error with CUDA 10.0

### ISSUE THREAD

**Issue by guillaumekln** [NVIDIA/cub#439]
Hello,

I'm using this project via Thrust 1.16.0 and I get the following compilation error with CUDA 10.0 when including `cub/cub.cuh`:

```text
thrust/dependencies/cub/cub/detail/temporary_storage.cuh(305): error: identifier "cudaErrorAlreadyMapped" is undefined
```

Is CUDA 10.0 still supported by recent versions?

Thanks!

**Comment by allisonvacanti** [comment]
The current version of Thrust requires at least CTK 11.0.
