### ISSUE TITLE
how to build on cuda10.2?

### ISSUE THREAD

**Issue by jinfagang** [NVIDIA/cub#443]
cuda10.2 doesnt support gpu arch 80

**Comment by allisonvacanti** [comment]
Correct, CUDA 10.2 doesn't support Ampere, you'll need a newer version of CTK for that. Is there a CUB issue here?

**Comment by jinfagang** [comment]
@allisonvacanti I cloned cub and build it got this error.

**Comment by allisonvacanti** [comment]
The current development branch of CUB only supports CUDA 11.0+. The 1.8.0 version of CUB should work on 10.2.
