### ISSUE TITLE
cub device scan is not deterministic as described in the documentation

### ISSUE THREAD

**Issue by zasdfgbnm** [NVIDIA/cub#454]
Issue originally reported at https://github.com/pytorch/pytorch/issues/75240
To repro, see: https://github.com/NVIDIA/cub/pull/453

**Comment by wence-** [comment]
FWIW, https://github.com/NVIDIA/cub/commit/7a8320c3ab1aa0d73946f443036c20edf85f68be updates the docs to indicate that these operations are not deterministic run-to-run. But it looks like there hasn't been a release to build them since then?

**Comment by allisonvacanti** [comment]
Unfortunately this issue has been popping up a lot recently in several algorithms, scan and reduce variants in particular. It appears that this documentation has been incorrect for quite some time, as these algorithms are implemented using techniques like decoupled lookback that are completely non-deterministic.

I'm aware of the situation and would like to fix it, but currently lack the resources needed to address these problems. This situation should hopefully improve in the next few months and ideally we'll be able to provide deterministic versions of these algorithms at some point.

**Comment by allisonvacanti** [comment]
Wrote up a summary of the issue and some proposed solutions in #471. Feedback is welcome -- closing this issue to consolidate discussion to the new issue.
