### ISSUE TITLE
Sorting of non-contiguous segments. Guarantees for ranges not specified in offsets?

### ISSUE THREAD

**Issue by fkallen** [NVIDIA/cub#485]
Assume that there is a contiguous range of 100 elements, and two segments [0 - 10), [80-100) should be sorted using the DoubleBuffer overload (using either segmented sort or segmented radix sort).

Does cub guarantee that elements 10 -79 remain unmodified in both Current() and Alternate() buffers?

**Comment by senior-zero** [comment]
Hello, @fkallen! That's a good question. As I understand, the only requirement that documentation has to the segments is that they shouldn't overlap. We don't have any tests to ensure the mentioned behaviour. Do you have a use case that would require such a guarantee? If so, we should update the documentation along with tests.

**Comment by leofang** [comment]
I suppose if a strong guarantee is needed, we may have to use the non-`DoubleBuffer` overload?
