### ISSUE TITLE
Support more generic scan_op in device_scan

### ISSUE THREAD

**Issue by cctry** [NVIDIA/cub#526]
Will cub support using more generic scan_op such as `T1 operator()(T1 &a, T2 &b)` ? The use case is to scan on an array of structs and calculate based on structs' members. 
Is there any suggestion on implementing such a primitive?

**Comment by elstehle** [comment]
>  Is there any suggestion on implementing such a primitive?

A common pattern to resolve the situation you are describing is to use a [`cub::TransformInputIterator`](https://nvlabs.github.io/cub/classcub_1_1_transform_input_iterator.html) and/or [`thrust::transform_output_iterator`](https://thrust.github.io/doc/classthrust_1_1transform__output__iterator.html). If you're able to provide more details of what exactly you're trying to achieve, we may be able to assess whether that could work in your case and provide more guidance on how the iterators could be applied.

**Comment by allisonvacanti** [comment]
Closing as @elstehle's answer will work currently, and @senior-zero covered a future improvement in this area. Let us know if you have any other questions about this.
