### ISSUE TITLE
Bump minimal supported NVHPC version

### ISSUE THREAD

**Issue by senior-zero** [NVIDIA/cub#540]
We currently require NVC++ 20.9+. The tests fail to compile with this version for a while. I suggest we bump nvhpc version to 22.3 as part of 2.0 release.

**Comment by brycelelbach** [comment]
That sounds fine.

**Comment by allisonvacanti** [comment]
We discussed this a bit more offline, and will just remove the reference to nvhpc. We do not support users leveraging nvc++ as a CUDA compiler for Thrust/CUB.
