### ISSUE TITLE
Use libcu++ atomics in CUB

### ISSUE THREAD

**Issue by senior-zero** [NVIDIA/cub#560]
There were a couple of issues related to the fact that CUB doesn't use atomic abstractions internally: [1](https://github.com/NVIDIA/cub/issues/345), [2](https://github.com/NVIDIA/cub/issues/356). Atomics usage would allow us to update code like:
```cpp
do {
  status = ThreadLoad<LOAD_CG>(d_tile_status + TILE_STATUS_PADDING + tile_idx);
  __threadfence();    // prevent hoisting loads from loop or loads below above this one

} while (status == SCAN_TILE_INVALID);
```

Technically, there's no issue at the moment, but using libcu++ atomics would:
1) improve readability - explicit memory ordering guarantee communicates intent better
2) potentially provide better performance

Since CUB 2.0, we have libcu++ as a dependency, so the replacement is getting possible. I'd like to use `atomic_ref` here. which is C++20, but it seems to be backported all the way to C++11. So there's no blocker here. The only issue would be that libcu++ atomics require sm60+ and we support devices since sm35. @wmaxey is my analysis on applicability libcu++ atomics in CUB correct here?

**Comment by allisonvacanti** [comment]
I believe this is a duplicate of #227.

> The only issue would be that libcu++ atomics require sm60+ and we support devices since sm35.

This was the blocker for switching to `cuda::std::atomic`. We could potentially switch to `cuda::std::atomic_ref` now that it's available, but would need to fallback to legacy atomics on older arches.

**Comment by senior-zero** [comment]
@allisonvacanti thanks, I've missed that issue! I'll close this one. 
> This was the blocker for switching to cuda::std::atomic

Minimal arch is inherited by `cuda::std::atomic_ref` as well, so there seems to be no difference between it and `cuda::std::atomic`. 

> would need to fallback to legacy atomics on older arches

I don't think there are legacy atomics for loads/stores with qualifiers. Do you mean inline PTX? In any case, I think it would be preferable to understand what is particularly limiting `cuda::std::atomic_ref` in [sm35, sm53] support and point that out in #227 as a blocker. There's a high chance that `load` and `store` are usable there, and the limitation if for other algorithms. @wmaxey is this the case?

**Comment by allisonvacanti** [comment]
> Minimal arch is inherited by `cuda::std::atomic_ref` as well, so there seems to be no difference between it and `cuda::std::atomic`.

The reason we were waiting for `atomic_ref` vs `atomic` was to simplify the code divergence between pre-sm60 and post-sm60. `atomic` would require changing the type of the atomic variables, while `atomic_ref` only modifies the callsite of the atomics. It's far less invasive and more compatible with if-target to use `atomic_ref` instead of `atomic<T>` with the legacy fallbacks for older arches.

> I don't think there are legacy atomics for loads/stores with qualifiers.

The qualifiers and memory ordering would need to take advantage of the "these are just hints, and stronger semantics may be used" loophole for the legacy case :)
