### ISSUE TITLE
thrust cuda kernel launch

### ISSUE THREAD

**Issue by hlq1025** [NVIDIA/cub#561]
@dkolsen-pgi  Hi, I noticed that this commit is a bug fix. could you explain about the bufg in detail.Thanks. https://github.com/NVIDIA/cub/commit/35e4f6982809a9caa4493c8169e71925b4d69d03,

**Comment by dkolsen-pgi** [comment]
It was not a bug fix.  That commit was one small part of the work necessary to enable running standard C++ parallel algorithms on GPUs with the NVC++ compiler.
