### ISSUE TITLE
Question: how lookback used in scan avoid loading stale data in L1 cache?

### ISSUE THREAD

**Issue by PanZaifeng** [NVIDIA/cub#591]
I got confused when reading the code in `agent/single_pass_scan_operators.cuh`.
There is one block that stores the tile data and then updates the status in `SetInclusive` and `SetPartial`:

```cuda
  /**
   * Update the specified tile's partial value and corresponding status
   */
  __device__ __forceinline__ void SetPartial(int tile_idx, T tile_partial)
  {
      // Update tile partial value
      ThreadStore<STORE_CG>(d_tile_partial + TILE_STATUS_PADDING + tile_idx, tile_partial);

      // Fence
      __threadfence();

      // Update tile status
      ThreadStore<STORE_CG>(d_tile_status + TILE_STATUS_PADDING + tile_idx, StatusWord(SCAN_TILE_PARTIAL));
  }
```

Another block waits for the status becomes valid and then loads the tile data in `WaitForValid`:
```cuda
  /**
   * Wait for the corresponding tile to become non-invalid
   */
  __device__ __forceinline__ void WaitForValid(
      int             tile_idx,
      StatusWord      &status,
      T               &value)
  {
      do {
          status = ThreadLoad<LOAD_CG>(d_tile_status + TILE_STATUS_PADDING + tile_idx);

          __threadfence();    // prevent hoisting loads from loop or loads below above this one

      } while (status == SCAN_TILE_INVALID);

      if (status == StatusWord(SCAN_TILE_PARTIAL)) 
          value = ThreadLoad<LOAD_CG>(d_tile_partial + TILE_STATUS_PADDING + tile_idx);
      else
          value = ThreadLoad<LOAD_CG>(d_tile_inclusive + TILE_STATUS_PADDING + tile_idx);
  }
```

I think the code above is unsafe, as the `value` loaded from `d_tile_partial` or `d_tile_inclusive` may be stale. 
As mentioned in [PTX cache operators](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#cache-operators), cache modifiers are only treated as performance hints.
Hence, `value` here can be the one in L1 cache, which may be inconsistent with the L2 cache and global memory, if the two blocks are running on different SMs.

Is it possible for this to happen and cause wrong results?

**Comment by senior-zero** [comment]
Hello, @PanZaifeng! 

As you can notice, there's a `__threadfence` between setting the data and setting the flag. On the other side, there's a `__threadfence()` between reading the flag and reading the data. Memory fences ensure that the memory is actually read and written without reordering or caching. In the PTX doc you referred to, there's a [8.8. Release and Acquire Patterns](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#release-acquire-patterns) section that describes acquire/release patterns that you might be interested in.

**Comment by PanZaifeng** [comment]
Thanks for your reply @senior-zero.

> Memory fences ensure that the memory is actually read and written without reordering or caching.

Does this means that the L1 cache is flushed or updated after `__threadfence()`?

[CUDA programming guide B.5](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#memory-fence-functions) mentions that

> Memory fence functions only affect the ordering of memory operations by a thread; they do not, by themselves, ensure that these memory operations are visible to other threads (like __syncthreads() does for threads within a block (see [Synchronization Functions](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#synchronization-functions))). In the code sample below, the visibility of memory operations on the result variable is ensured by declaring it as volatile.

If fence function can affect the cache, what does the "visible" here means? Can we only use fence functions here to ensure the correctness, without declaring `result` variable as `volatile`?

**Comment by senior-zero** [comment]
It happened that I had misconceptions about thread fences and weak memory operations. Your concern is valid. Thank you for reporting it! We shouldn't rely on CG hint here. We'll fix this at our earliest capacity. Please let us know if you find other instances of this, we’d like to fix those as well.
