### ISSUE TITLE
Backport fixes for reordering in CUB member initializer lists into 2.0 branch

### ISSUE THREAD

**Issue by senior-zero** [NVIDIA/cub#604]
There's a request to port the following [fix](https://github.com/NVIDIA/cub/pull/582) into 2.0 branch.

**Comment by ericniebler** [comment]
@senior-zero Is the target still the 2.0 branch (`2.0.X`), or should I be targeting the `2.1.x` branch?

**Comment by senior-zero** [comment]
@ericniebler the fix is available in 2.1. The request was to backport it into 2.0.

**Comment by senior-zero** [comment]
Addressed as part of the following [PR](https://github.com/NVIDIA/cub/pull/681).
