### ISSUE TITLE
Compiler error with CUDA <11.5 due to int128 

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cub#629]
Simply including `cub/cub.cuh` will fail with `nvcc < 11.5` complaining about using `__(u)int128_t` in device code:

>  error: "__uint128_t (__uint128_t)" contains a 128-bit integer, which is not supported in device code

Repro: https://godbolt.org/z/5bGnbehsT 

It looks like the CUDA version check guarding use of `__(u)int128` has a logic error: 
https://github.com/NVIDIA/cub/blob/5d12837f92ee12016827ad6f1ccbbc963eb428ff/cub/util_type.cuh#L65

I believe it should be:
```
#if (__CUDACC_VER_MAJOR__ >= 11 && CUDA_VERSION >= 11050)
```

Otherwise the `__CUDACC_VER_MAJOR__ >= 11` will always be true for any 11.* compiler and `CUB_IS_INT128_ENABLED` will be defined.

**Comment by senior-zero** [comment]
Has been fixed in the following [PR](https://github.com/NVIDIA/cub/pull/630).
