### ISSUE TITLE
Can cub::DeviceSegmentedReduce::Reduce support self-defined functor for struct variable instead of just integer?

### ISSUE THREAD

**Issue by zlwu92** [NVIDIA/cub#666]
Hi,

I want to know if the cub::DeviceSegmentedReduce::Reduce support for struct variable, the source code example in comments I found is for integer. 

Suppose we have two integer in the struct, one is id, one is value, firstly we compare value, choose the min, if two values are equal then we choose the minimal id, that's basically two levels of comparison in my self-defined functor.

Btw, if the warp level scan can pass a self-defined customized functor into it? And if this can support arbitrary length or just 32 which is equal to warpsize.
```[tasklist]
```

**Comment by senior-zero** [comment]
Hello @zlwu92!

I noticed that you've been asking questions in the issues section again. In the [previous](https://github.com/NVIDIA/cub/issues/644#issuecomment-1484027990) interaction, I kindly requested that you use the GitHub Discussions feature for asking questions and engaging in discussions. Please use the Discussions tab for your future questions, as it helps us maintain a more organized and efficient repository. By doing so, we can ensure that the issues section remains focused on addressing bugs and feature requests. Here's the link to our repository's Discussions tab for your convenience: https://github.com/NVIDIA/cub/discussions

**Comment by zlwu92** [comment]
Ok, I see. Sorry. I will make it into discussions.
