### ISSUE TITLE
Misleading documentation for DeviceSegmentedRadixSort (or I'm using it wrong)

### ISSUE THREAD

**Issue by HapeMask** [NVIDIA/cub#731]
The docstrings for sorting methods on `DeviceSegmentedRadixSort` state that the `num_items` parameter should contain, "The total number of items to sort (across all segments)."

Consider this toy example:

```cuda
int d_keys_in[]        = {3, 2, 1, 0, 0, 0, 4, 5, 6};
int d_values_in[]      = {1, 2, 3, 0, 0, 0, 6, 5, 4};

int d_segment_starts[] = {0, 6}; // These define two non-contiguous segments.
int d_segment_ends[]   = {3, 9}; // Each segment is of length 3.
                                 // There are 6 total items to sort across all segments.
```

After reading the documentation, I would pass 6 as the value for `num_items` since there are 6 items across the segments I have defined. If I do this with real data though, and call `DeviceSegmentedRadixSort::SortPairs()`, it will perform an illegal memory access. If I pass the total size of the key array, instead of the number of items to sort, then it does not perform any illegal memory accesses (confirmed in both cases with `cuda-memcheck`). I've attached a simple repro below which performs invalid global writes, tested on a V100 GPU using CUB 1.12.1 and 1.13.

```cuda
#include <cub/cub.cuh>

int main(int argc, char** argv) {
  const int N = 1024;
  int* values = new int[N];
  int* keys = new int[N];
  int range_begin[] = {0, 512};
  int range_end[] = {128, 640};
  int num_items = range_end[0] - range_begin[0] + range_end[1] - range_begin[1];
  int num_segments = 2;

  int* d_keys;
  int* d_keys_sorted;
  int* d_values;
  int* d_values_sorted;
  int* d_range_begin;
  int* d_range_end;
  cudaMalloc((void**)&d_keys, N * sizeof(int));
  cudaMalloc((void**)&d_keys_sorted, N * sizeof(int));
  cudaMalloc((void**)&d_values, N * sizeof(int));
  cudaMalloc((void**)&d_values_sorted, N * sizeof(int));
  cudaMalloc((void**)&d_range_begin, num_segments * sizeof(int));
  cudaMalloc((void**)&d_range_end, num_segments * sizeof(int));

  cudaMemset(d_keys_sorted, 0, N * sizeof(int));
  cudaMemset(d_values_sorted, 0, N * sizeof(int));
  cudaMemcpy(d_keys, keys, N * sizeof(int), cudaMemcpyHostToDevice);
  cudaMemcpy(d_values, values, N * sizeof(int), cudaMemcpyHostToDevice);
  cudaMemcpy(d_range_begin, range_begin, num_segments * sizeof(int), cudaMemcpyHostToDevice);
  cudaMemcpy(d_range_end, range_end, num_segments * sizeof(int), cudaMemcpyHostToDevice);

  void* d_temp_storage = nullptr;
  size_t temp_storage_bytes = 0;
  cub::DeviceSegmentedRadixSort::SortPairs(d_temp_storage, temp_storage_bytes,
    d_keys, d_keys_sorted,
    d_values, d_values_sorted,
    num_items, num_segments, d_range_begin, d_range_end);

  cudaMalloc(&d_temp_storage, temp_storage_bytes);

  cub::DeviceSegmentedRadixSort::SortPairs(d_temp_storage, temp_storage_bytes,
    d_keys, d_keys_sorted,
    d_values, d_values_sorted,
    num_items, num_segments, d_range_begin, d_range_end);

  return 0;
}
```

I was going to create a PR correcting the docstrings, but I'm not 100% sure if I'm misusing the library somehow?

**Comment by senior-zero** [comment]
Hello @HapeMask and thank you for a noticing this! The documentation is indeed ambiguous when segments do not cover all the segments. The segmented sort processes segments (specified by offsets) of an array which size has to be provided as `num_items`. We would be happy to accept your contribution. One note, though. If you decide to open a PR, please, do so against https://github.com/NVIDIA/cccl.
