### ISSUE TITLE
Possible bug in variable naming

### ISSUE THREAD

**Issue by akshit-sharma** [NVIDIA/cub#743]
The variable at [agent_batch_memcpy.cuh:864](https://github.com/NVIDIA/cub/blob/b2e8bccb8c0cd15279974fe4b9b8d6fcd1842b57/cub/agent/agent_batch_memcpy.cuh#L864) seems to have name `WARPS_PER_BLOCK`. The problem can be all caps are mostly used for Macro names, and somebody defining WARPS_PER_BLOCK macro in their code makes the code uncompilable.

**Comment by miscco** [comment]
This is a historical artefact and we have a ton of template arguments that are named in UPPERCASE.

While not conventional, changing this would require a lot of work for minimal gain and potential fragmentation within the codebase.

The names used are rather few and highly specific to cuda, so we will most likely leave this as is.

If there are widespread issues comming from this naming convention we can investigate, but for now I would close this issue

**Comment by miscco** [comment]
Also note that we have moved cub to the https://github.com/NVIDIA/cccl repo, where we have cub, thrust and libcu++ in one single repository, so if there are any future issues please file them over there
