### ISSUE TITLE
[Feature request] Persist RadixSort passes or efficient cache friendly  gather implemenation 

### ISSUE THREAD

**Issue by sh1ng** [NVIDIA/cub#82]
My data type is integer and each value contains a left part of a certain size plus a right part.
Right part stays constant during iteration(letter on I'll clarify it)
So an example may look like

`llllllrrrrrr`
where `l` - bit from a left part and `r` - bit from a right part.

My algorithm looks like
```
loop # iteration over data, the right part stays the same along the iterations
    Radix sort
```

To not repeat sorting by the right part at the each iteration I've decided to  do the following
```

Sort data by the right part and get gather index
loop
   apply gather kernel that places each element at appropriate position(make data sorted by the right part)
   Radix sort by the left part
```

Unfortunately it reduces the performance(at least where data size > 10M). I can explain it by the fact that random memory access on GPU is pretty inefficient and it's faster to do a few less random passes than one completely random pass. 

But I still want to improve my implementation(by not doing the same operation multiple times).
Is it possible to save passes itself without doing the whole sort?
Or improve gather kernel in more efficient way? It's ok if it requires auxiliary memory (a will anyway allocate it for RadixSort).

What do you think?

**Comment by allisonvacanti** [comment]
You may have better luck getting input on algorithm design by asking on StackOverflow, but this is beyond the scope of a GitHub issue.

If there's a specific feature request, please file a new issue with a clearer description of what you're looking for.
